### ISSUE TITLE
Version referenced in sample app is not in sync

### ISSUE THREAD

**Issue by altenhof** [SAP/cf-java-logging-support#40]
We tend to forget to bump the reference to the library version in the sample [pom.xml](https://github.com/SAP/cf-java-logging-support/blob/master/sample/pom.xml#L21). This time, it's a real deal breaker as the app will crash with:
```
Caused by: java.lang.NoClassDefFoundError: com/sap/hcp/cf/logging/common/converter/DefaultArgsConverter
	at com.sap.hcp.cf.log4j2.converter.ArgsConverter.<init>(ArgsConverter.java:26)
	at com.sap.hcp.cf.log4j2.converter.ArgsConverter.newInstance(ArgsConverter.java:38)
	... 69 more
Caused by: java.lang.ClassNotFoundException: com.sap.hcp.cf.logging.common.converter.DefaultArgsConverter
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1293)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1145)
	... 71 more
```
I suggest that we fix this once and for all, either be removing this line or changing it to
```
        <cf-logging.version>${project.version}</cf-logging.version>
```
Anybody any preferences?

**Comment by anklei** [comment]
I'd vote for ${project.version}
