### ISSUE TITLE
Update logback-classic version

### ISSUE THREAD

**Issue by C-Otto** [SAP/cf-java-logging-support#6]
The logback configuration example references version 1.1.3 of logback-classic. With that I get the exception show below upon startup. With versions 1.1.6 or later it works as expected.

```
Failed to instantiate [ch.qos.logback.classic.LoggerContext]
Reported exception:
java.lang.NoSuchMethodError: ch.qos.logback.core.util.Loader.getResourceOccurrenceCount(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/util/Set;
	at ch.qos.logback.classic.util.ContextInitializer.multiplicityWarning(ContextInitializer.java:173)
	at ch.qos.logback.classic.util.ContextInitializer.statusOnResourceSearch(ContextInitializer.java:196)
	at ch.qos.logback.classic.util.ContextInitializer.getResource(ContextInitializer.java:143)
	at ch.qos.logback.classic.util.ContextInitializer.findURLOfDefaultConfigurationFile(ContextInitializer.java:137)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:85)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:155)
	at org.apache.commons.logging.impl.SLF4JLogFactory.getInstance(SLF4JLogFactory.java:132)
	at org.apache.commons.logging.LogFactory.getLog(LogFactory.java:273)
	at org.springframework.boot.SpringApplication.<clinit>(SpringApplication.java:190)
```

**Comment by altenhof** [comment]
Hi @C-Otto,

I assume that you're referring to the example in the `README.md` file, right? 

While I could certainly correct the version number there, I'm wondering whether you have more info on why that failed in your case. Looking at the stack trace, I conclude that you're using Spring Boot, so is there any reference in the Spring Boot documentation that indicates which logback version could or should be used?

On the other hand doesn't Spring Boot itself already specifies a dependency to logback?

Best

Michael

**Comment by C-Otto** [comment]
Yes to both: I'm referring to the README, and I'm running Spring Boot for now.

In `spring-boot-starter` I get `spring-boot-starter-logging`. This includes logback. The current Spring Boot release 1.4 references logback in version 1.1.7. When using this (instead of explicitly excluding it from `spring-boot-starter` and importing according to the README) everything works as intended.

I think this is how it really should be done, so I'm closing this as invalid. Maybe you want to mention that the import is not necessary (or even harmful) for Spring Boot?
